
import * as d from './proxy';

export const DIRECTIVES = [
  d.AmalitechAccordion,
  d.AmalitechAlert,
  d.AmalitechAlertContent,
  d.AmalitechBreadcrumb,
  d.AmalitechBreadcrumbItem,
  d.AmalitechButton,
  d.AmalitechCard,
  d.AmalitechCheckbox,
  d.AmalitechDataTable,
  d.AmalitechDatePicker,
  d.AmalitechDockedUtilityBar,
  d.AmalitechDockedUtilityBody,
  d.AmalitechDockedUtilityItem,
  d.AmalitechInput,
  d.AmalitechMap,
  d.AmalitechModal,
  d.AmalitechNavItem,
  d.AmalitechNavMobile,
  d.AmalitechNavbar,
  d.AmalitechPagination,
  d.AmalitechProgress,
  d.AmalitechProgressBar,
  d.AmalitechProgressRing,
  d.AmalitechRadioButton,
  d.AmalitechRadioGroup,
  d.AmalitechSelect,
  d.AmalitechSelectMultiple,
  d.AmalitechSelectOption,
  d.AmalitechSelectSingle,
  d.AmalitechSnackbar,
  d.AmalitechStarRating,
  d.AmalitechSwitch,
  d.AmalitechTab,
  d.AmalitechTabPanel,
  d.AmalitechTimePicker,
  d.AmalitechTree,
  d.AmalitechTreeNode,
  d.AmalitechValidation,
  d.AmalitechVisualPicker,
  d.AmalitechVisualPickerItem
];
